// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Balance struct {
	ID        int32              `json:"id"`
	Lender    int32              `json:"lender"`
	Borrower  int32              `json:"borrower"`
	GroupID   int32              `json:"group_id"`
	Amount    pgtype.Numeric     `json:"amount"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Expense struct {
	ID          int32              `json:"id"`
	GroupID     int32              `json:"group_id"`
	PaidBy      int32              `json:"paid_by"`
	Amount      pgtype.Numeric     `json:"amount"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Group struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedBy   int32              `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Member struct {
	ID       int32              `json:"id"`
	UserID   int32              `json:"user_id"`
	GroupID  int32              `json:"group_id"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type User struct {
	ID        int32              `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
